<a href="https://colab.research.google.com/github/jcmm518/AprendizajeNoSupervisado/blob/main/Programa2_Estandarizacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import preprocessing
import numpy as np

In [ ]:
# Carga de datos.
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [ ]:
# Limpieza de datos: estandarización.
standardizer = preprocessing.StandardScaler()
X_train_std = standardizer.fit_transform(X_train)

In [ ]:
# Salida de resultados.
print(X_train_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]
